name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: .
          file: ./infrastructure/php/Dockerfile
          tags: gsdevme/glasgow-bin-collection-mqtt:${{ github.sha }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: gsdevmebot
          password: ${{ secrets.DOCKER_HUB }}
      - name: Build
        id: docker_push
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/master'
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          file: ./infrastructure/php/Dockerfile
          tags: gsdevme/glasgow-bin-collection-mqtt:latest
